import { ActionConfig, AssetType, ImpactSummary } from "../types";

const DISPLAY_LABELS: Record<AssetType, string> = {
  dashboard: "Dashboards",
  pipeline: "Pipelines",
  report: "Reports",
  table: "Tables",
  view: "Views",
  topic: "Topics",
  other: "Other Assets",
};

const ORDER: AssetType[] = [
  "dashboard",
  "pipeline",
  "report",
  "table",
  "view",
  "topic",
  "other",
];

function capitalizeRisk(risk: ImpactSummary["riskLevel"]): string {
  return risk.charAt(0).toUpperCase() + risk.slice(1);
}

function renderAssetRows(summary: ImpactSummary, config: ActionConfig): string[] {
  const rows: string[] = [];

  for (const type of ORDER) {
    const assets = summary.impactedByType[type];
    if (assets.length === 0) {
      continue;
    }

    rows.push(`### ${DISPLAY_LABELS[type]} (${assets.length})`);
    const slice = assets.slice(0, config.maxCommentAssets);
    for (const asset of slice) {
      const linkOrName = asset.url ? `[${asset.name}](${asset.url})` : asset.name;
      const reason = asset.reasons[0] ?? "Downstream dependency";
      rows.push(`- ${linkOrName} (${asset.fqn})`);
      rows.push(`  - Reason: ${reason}`);
    }

    if (assets.length > config.maxCommentAssets) {
      rows.push(
        `- ... and ${assets.length - config.maxCommentAssets} more ${DISPLAY_LABELS[type].toLowerCase()}.`,
      );
    }

    rows.push("");
  }

  return rows;
}

export function renderImpactComment(summary: ImpactSummary, config: ActionConfig): string {
  const lines: string[] = [];
  lines.push("## Data Impact Analysis");
  lines.push("");
  lines.push("### Summary");
  lines.push(`- Risk: **${capitalizeRisk(summary.riskLevel)}**`);
  lines.push(`- Changed entities: **${summary.changedEntityCount}**`);
  lines.push(`- Impacted downstream assets: **${summary.impactedAssetCount}**`);
  lines.push(`- Warnings: **${summary.warnings.length}**`);
  lines.push("");

  if (summary.aiSummary) {
    lines.push("### Optional AI Summary");
    lines.push(summary.aiSummary);
    lines.push("");
  }

  const assets = renderAssetRows(summary, config);
  if (assets.length > 0) {
    lines.push("### Impacted Assets");
    lines.push("");
    lines.push(...assets);
  } else {
    lines.push("### Impacted Assets");
    lines.push("");
    lines.push("No downstream assets were identified from available lineage data.");
    lines.push("");
  }

  if (summary.warnings.length > 0) {
    lines.push("### Warnings");
    for (const warning of summary.warnings) {
      lines.push(`- ${warning}`);
    }
    lines.push("");
  }

  if (summary.suggestions.length > 0) {
    lines.push("### Suggestions");
    for (const suggestion of summary.suggestions) {
      lines.push(`- ${suggestion}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("Generated by OpenMetadata Impact Analysis Action");

  return lines.join("\n").trim();
}
